### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lauaall** [leekycauldron/csgo-bomb#1]
Hey,
I wanna recreate the bomb and I've got a few questions. Btw I
got the exact same parts that you used.

How did you wire the keypad? If possible with a picture of the Arduino Uno and the Matrix 3x4 keypad side to side. 

,Thanks

**Comment by leekycauldron** [comment]
https://electropeak.com/learn/interfacing-4x3-membrane-matrix-keypad-with-arduino/

The order of the pins is here... lmk if u got questions.

BTW, this is the site I used.

**Comment by lauaall** [comment]
Interesting, I've already tried that wiring and got the # to only work. Maybe wasn't something correct.

**Comment by leekycauldron** [comment]
Maybe an issue with the code? Follow this... https://arduinogetstarted.com/tutorials/arduino-keypad

**Comment by lauaall** [comment]
I think I might have an broken keypad. When I press the # it turns on the TX led on my Uno, and any other number or symbol doesn't activate the led. I put a test program on it and it only logs the * sign.
![image](https://user-images.githubusercontent.com/48836917/233147065-2e227dd9-7e11-4c6c-af73-4b2ccab2c308.png)

**Comment by leekycauldron** [comment]
Maybe send a pic of how you wired it?

**Comment by lauaall** [comment]
Here:
![image](https://user-images.githubusercontent.com/48836917/233149167-f34eae59-057d-4141-abc7-cb5c8fd8204a.jpeg)

**Comment by leekycauldron** [comment]
Careful with how you soldered it, your connections may be touching you want to make sure they don't touch. I had that problem too.

**Comment by lauaall** [comment]
> Careful with how you soldered it, your connections may be touching you want to make sure they don't touch. I had that problem too.

I just checked, none seem to be connect with each other. I'm gonna unsolder and try again.

**Comment by lauaall** [comment]
It has to be defective, just finished resoldering and tested it, now it sends NOTHING.

**Comment by leekycauldron** [comment]
<img width="190" alt="Screenshot 2023-04-19 175209" src="https://user-images.githubusercontent.com/48774118/233208226-cba8b61f-85ad-4d40-800f-b73ea6416a93.png">

Here it looks like they are touching... idk maybe the angle is bad. Just make sure all the wires are spread as far apart as possible or maybe tape each one individually, even touching it a little can mess the whole thing up.

**Comment by lauaall** [comment]
> <img width="190" alt="Screenshot 2023-04-19 175209" src="https://user-images.githubusercontent.com/48774118/233208226-cba8b61f-85ad-4d40-800f-b73ea6416a93.png">
> 
> 
> 
> Here it looks like they are touching... idk maybe the angle is bad. Just make sure all the wires are spread as far apart as possible or maybe tape each one individually, even touching it a little can mess the whole thing up.
> 
> 

Yeah ,I de-soldered every single one yesterday and did it again.
